name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-go@v3
      with:
        go-version: '1.22'

    - name: Install Gomobile
      run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - uses: kaisugi/action-regex-match@v1.0.0
      id: regex-match
      with:
        text: ${{ github.event.head_commit.message }}
        regex: '^v[0-9]+\.[0-9]+\.[0-9]+$'

    - name: Sign App
#      if: ${{ steps.regex-match.outputs.match != '' }}
      id: sign_app
      uses: ilharp/sign-android-release@v1.0.4
      with:
        releaseDir: app/build/outputs
        signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
        keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

    - name: Build Changelog
#      if: ${{ steps.regex-match.outputs.match != '' }}
      id: changelog
      uses: ardalanamini/auto-changelog@v3
      with:
        mention-authors: false
        mention-new-contributors: false
        include-compare: false
        semver: false

    - name: Create Release
#      if: ${{ steps.regex-match.outputs.match != '' }}
      id: create_release
      uses: ncipollo/release-action@v1.13.0
      with:
        artifacts: ${{steps.sign_app.outputs.signedReleaseFile}}
        body: ${{ steps.changelog.outputs.changelog }}
        tag: ${{ github.event.head_commit.message }}
        name: Release ${{ github.event.head_commit.message }}
#        token: ${{ secrets.GITHUB_TOKEN }}

#    - name: Release the Package
#      uses: softprops/action-gh-release@v2
#      with:
#        files: openfortivpn*.deb

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: .
        retention-days: 5

    - name: LS
      run: |
          ls -l app/build
          ls -l app/build/generated
          ls -l app/build/kotlin
          ls -l app/build/tmp
